### ISSUE TITLE
No annotation scores in web service response

### ISSUE THREAD

**Issue by bernhardschaefer** [AKSW/AGDISTIS#1]
Hello,
I added AGDISTIS to the annotators in the BAT framework[1] by Cornolti et al.[2].
However, since AGDISTIS does not return a score for each annotation, the scored annotation problems cannot be evaluated.
Are there any plans on including annotation scores in the web service response, e.g. based on HITS scores?

[1] https://github.com/marcocor/bat-framework
[2] http://dl.acm.org/citation.cfm?id=2488411

**Comment by RicardoUsbeck** [comment]
I close this issue for now. Thanks for using AGDISTIS! Please let us know if there is anything else we can do. Moreover, just as a general pointer, there is GERBIL (https://gerbil.aksw.org) for further evaluations.
