### ISSUE TITLE
Building my own index and surfaceform tsv file

### ISSUE THREAD

**Issue by vishalpai** [AKSW/AGDISTIS#13]
Hi,

I am looking at the below url (Running the web service)
https://github.com/AKSW/AGDISTIS/wiki/3-Running-the-webservice

In create your own index section, from where do I get the file for the property 'surfaceFormTSV'. 

Best Regards,
Vishal

**Comment by lezakkaz** [comment]
Hey there,

Im just a researcher, you should email uzbec he is the guy who can help. I tried to download that file as well but it didnt work for me.
If youre working on AGDISTIS then please keep in touch so we can share information. 

Regards,
Zakaria

<div>-------- Original message --------</div><div>From: vishalpai <notifications@github.com> </div><div>Date:2015/07/04  1:42 PM  (GMT+09:00) </div><div>To: AKSW/AGDISTIS <AGDISTIS@noreply.github.com> </div><div>Subject: [AGDISTIS] Building my own index and surfaceform tsv file (#13) </div><div>
</div>Hi,

I am looking at the below url (Running the web service)
https://github.com/AKSW/AGDISTIS/wiki/3-Running-the-webservice

In create your own index section, from where do I get the file for the property 'surfaceFormTSV'.

Best Regards,
Vishal

**Comment by RicardoUsbeck** [comment]
Hi all, @lezakkaz, 

I updated https://github.com/AKSW/AGDISTIS/wiki/3-Running-the-webservice 

Surface forms are available here: http://139.18.2.164/rusbeck/agdistis/surfaceforms/

Or you create your own using http://aksw.org/Projects/BOA.html

Please let me know if you encounter anymore problems. 

Furthermore, if you do not mind, let me know on which projects you are working on. This would help my PhD thesis :)

**Comment by RicardoUsbeck** [comment]
I close this issue for now. Thanks for using AGDISTIS!
