### ISSUE TITLE
Disambiguated URL is null

### ISSUE THREAD

**Issue by suryahub** [AKSW/AGDISTIS#17]
Cloned the following project from github
https://github.com/AKSW/AGDISTIS and made configurations according to the following link

https://github.com/AKSW/AGDISTIS/wiki/3-Running-the-webservice

When tried to run the code used in AGIDISTISTest  for the following Preannotated Text,disambiguated URLs are null.
Text
<entity>Barack Obama</entity> visits <entity>Merkel</entity> in <entity>Berlin</entity>.

Please see the console
16:21:23,140 INFO [org.aksw.agdistis.algorithm.NEDAlgo_HITS] 64 - <Insert Candidates into Text>
16:21:23,141 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 70 - <	Label: Barack Obama>
16:21:23,196 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 132 - <		number of candidates before type reduction: 0>
16:21:23,197 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 214 - <Size of Reduced Candidates 0>
16:21:23,197 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 138 - <		number of candidates after type reduction: 0>
16:21:23,197 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 143 - <			No candidates for: Barack Obama>
Searching this label in surface forms..Barack Obama
16:21:23,277 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 132 - <		number of candidates before type reduction: 697>
16:21:23,401 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 214 - <Size of Reduced Candidates 0>
16:21:23,401 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 138 - <		number of candidates after type reduction: 0>
16:21:23,401 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 143 - <			No candidates for: Barack Obama>
16:21:23,401 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 78 - <	Graph size: 0 took: 260 ms>
16:21:23,401 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 70 - <	Label: Berlin>
16:21:23,402 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 132 - <		number of candidates before type reduction: 0>
16:21:23,402 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 214 - <Size of Reduced Candidates 0>
16:21:23,404 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 138 - <		number of candidates after type reduction: 0>
16:21:23,404 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 143 - <			No candidates for: Berlin>
Searching this label in surface forms..Berlin
16:21:23,428 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 132 - <		number of candidates before type reduction: 1000>
16:21:23,549 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 214 - <Size of Reduced Candidates 0>
16:21:23,549 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 138 - <		number of candidates after type reduction: 0>
16:21:23,551 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 143 - <			No candidates for: Berlin>
16:21:23,551 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 78 - <	Graph size: 0 took: 150 ms>
16:21:23,551 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 70 - <	Label: Merkel>
16:21:23,552 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 132 - <		number of candidates before type reduction: 0>
16:21:23,552 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 214 - <Size of Reduced Candidates 0>
16:21:23,552 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 138 - <		number of candidates after type reduction: 0>
16:21:23,552 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 143 - <			No candidates for: Merkel>
Searching this label in surface forms..Merkel
16:21:23,557 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 132 - <		number of candidates before type reduction: 93>
16:21:23,562 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 214 - <Size of Reduced Candidates 0>
16:21:23,562 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 138 - <		number of candidates after type reduction: 0>
16:21:23,562 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 143 - <			No candidates for: Merkel>
16:21:23,562 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 78 - <	Graph size: 0 took: 11 ms>
16:21:23,562 INFO [org.aksw.agdistis.algorithm.NEDAlgo_HITS] 69 - <	Graph size before BFS: 0>
16:21:23,563 INFO [org.aksw.agdistis.algorithm.NEDAlgo_HITS] 72 - <	Graph size after BFS: 0>
Merkel -> null
Barack Obama -> null
Berlin -> null

**Comment by RicardoUsbeck** [comment]
Dear @suryahub,

we are looking into that. Can you check out an earlier version. That is, 

`git checkout 690557b912f5ceec35ac992716c7a91dfa59b7d0` 

and run your test again?

**Comment by RicardoUsbeck** [comment]
We will make the latest master commit stable again. Meanwhile, I will close the ticket.

**Comment by DiegoMoussallem** [comment]
It is working again. @suryahub, you have to set the threshold 0.85, since we are using type reduction and it provides us more candidates than the usual around 10 times more. Also, I fixed a node.java class then i would like to ask you to pull again the project and check it.
