### ISSUE TITLE
How to work with plain text input in AGDISTIS

### ISSUE THREAD

**Issue by suryahub** [AKSW/AGDISTIS#19]
Hi,
   In the AGDISTIS sample code a preannoated text is given as input with the entities embedded inside entity Tags.Is there an option to give a plain text as input to AGDISTIS which automatically recognises entities and then do the disambiguation?I have heard about FOX.If the same can be done using FOX how do I integrate FOX with AGDISTIS?

Regards
suryahub

**Comment by RicardoUsbeck** [comment]
Please visit http://fox-demo.aksw.org/ or go to https://github.com/AKSW/fox which is maintained by @renespeck to use FOX as recognizer. Currently, FOX uses AGDISTIS also as disambiguation system.
