### ISSUE TITLE
Converting Natural Language to Database Queries

### ISSUE THREAD

**Issue by suryahub** [AKSW/AGDISTIS#20]
Hi,
Is there an option to integrate a database (SQL or NOSQL)with AGDISTIS and convert the natural language statements to database queries?
Eg:
    "invoices paid last year"
which inteprets the above sentence convert it to corresponding database queries and fetches the results from the database.
I found a similar usecase with dbpedia spotlight to convert natural language to SPARQL queries
https://dbpedia-spotlight.github.io/demo/

Is such a thing acheivable with AGDISTIS?

Regards
suryahub

**Comment by RicardoUsbeck** [comment]
Hi, 

AGDISTIS is just a knowledge base-agnostic named entity disambiguation engine. If you are looking for a natural language to SPARQL/SQL project please lookup "Question Answering systems" such as github.com/AKSW/NLIWOD, https://github.com/AKSW/openqa or join the community group https://www.w3.org/community/nli/.
