### ISSUE TITLE
Create a German, Chinese and English index.

### ISSUE THREAD

**Issue by DiegoMoussallem** [AKSW/AGDISTIS#30]
start three new dockers (one per language) and add a new demo docker for each one.

**Comment by DiegoMoussallem** [comment]
Chinese repositories haven't contained enough source files(disambiguations.ttl, redirects.ttl) since 2014. Therefore, Chinese index wasn't created.

**Comment by DiegoMoussallem** [comment]
@RicardoUsbeck, they are here -> http://139.18.2.164/dmoussallem/. Can I close this issue?

**Comment by RicardoUsbeck** [comment]
Could you please go through the wiki and the README and search for the old location? Then you can close this issue.
