### ISSUE TITLE
[400 Error] Python and CURL requests

### ISSUE THREAD

**Issue by Khalife** [AKSW/AGDISTIS#44]
Good afternoon everyone,

I am a new user and it seems that the API does not work when called from the official package agdistispy (400 error).

Also, the following request provides ERR_INVALID_URL :
curl --data-urlencode "text='<entity>Barack Obama</entity> arrives in <entity>Washington, D.C</entity>.'" -d type='agdistis' http://139.18.2.164:8080/AGDISTIS

I am located in France, but the API used to work yesterday.
Is it possible to tackle the issue?

Thanks in advance,

Sammy Khalife

**Comment by RicardoUsbeck** [comment]
Dear Sammy, 

can you try this where I marked an entity. Please note, you need to mark entities before disambiguating them with other tools such as AKSW/FOX.

curl --data-urlencode "text='Barack Obama arrives in <entity>Washington, D.C.</entity>'" -d type='agdistis' http://139.18.2.164:8080/AGDISTIS

**Comment by Khalife** [comment]
Dear Ricardo,

Thanks for your answer. I suppose you meant :

curl --data-urlencode "text='<entity>Barack Obama</entity> arrives in Washington, D.C.'" -d type='agdistis' http://139.18.2.164:8080/AGDISTIS

This one returns something without error now.
Have you fixed something in the server side?

Thanks again.

PS : I sent you a mail with more detailed questions. If for any reason you prefer me to copy/paste them here, I can do it.

**Comment by RicardoUsbeck** [comment]
Hi, 

I will have a look at your email alter today (sorry it is quite busy right now here). 

I corrected the example above, now there are entity markings. No, we did not correct anything. Maybe it was an error in our computing center network.

**Comment by DiegoMoussallem** [comment]
Could I close this issue? @Khalife

**Comment by Khalife** [comment]
Thanks Ricardo for your answer.
@DiegoMoussallem I close the issue.
