### ISSUE TITLE
Create a surface for a ranked list of URIs for surface forms

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/AGDISTIS#8]
As a user I not only want to see the URI that is most authoritative for a certain label but a ranked list of n possible URI candidates for labels.

It needs to be implemented as a webservice.

**Comment by DiegoMoussallem** [comment]
@RicardoUsbeck please check https://github.com/AKSW/AGDISTIS/tree/candidates and tell me if it was what you would want.

**Comment by RicardoUsbeck** [comment]
This is also relevant for #14

**Comment by RicardoUsbeck** [comment]
@filipdbrsk

**Comment by DiegoMoussallem** [comment]
Could we close it? @RicardoUsbeck

**Comment by RicardoUsbeck** [comment]
Could you paste the curl command for it here and then close it? @filipdbrsk I hope this is what you want?

**Comment by DiegoMoussallem** [comment]
curl --data-urlencode "text=Today, <entity>Barack Obama</entity> visited <entity>Berlin</entity> and met <entity>John Doe</entity>." -d type='candidates' http://localhost:8080/AGDISTIS/NED using mergeT branch.
