### ISSUE TITLE
"laparotomy" and "surgeon"

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/AGDISTIS#9]
Hi Ricardo,

Just to mention there might be something wrong with AGDISTIS.

I tried a sentence with "laparotomy" and "surgeon" and it did not provide a disambiguation (I put both terms in square brackets).

Greetings,

Denis

**Comment by DiegoMoussallem** [comment]
If you put with capital letter it works. thus it is related to https://github.com/AKSW/AGDISTIS/issues/10

**Comment by RicardoUsbeck** [comment]
solved by https://github.com/AKSW/AGDISTIS/commit/76454278445bb9fd1b13536e429b1be5f33dfc2b
